### ISSUE TITLE
Make setting relation more intuitive for to-one side

### ISSUE THREAD

**Issue by marktani** [graphcool/ui-feedback#1]
![ui-to-one-popup](https://cloud.githubusercontent.com/assets/1780597/24313985/983e39d0-10df-11e7-819a-c6be7b9a049c.png)

One idea is to allow users to choose a field on a related node [that acts as a label for nodes](https://github.com/graphcool/feature-requests/issues/86).

Maybe we can also think differently and make this easier in a different way.

**Comment by arrygoo** [comment]
+1

**Comment by marktani** [comment]
We have now a node selection popup.
