### ISSUE TITLE
"Add Field" and "Add Relation" buttons are too discrete on schema page

### ISSUE THREAD

**Issue by Thebigbignooby** [graphcool/ui-feedback#10]
i literally did not see those 2 buttons
![image](https://cloud.githubusercontent.com/assets/4172090/25185687/4d36a960-251e-11e7-9120-8dfa032c14b5.png)

I think the last row in table is where the "add field" button should be

I also expect to be able to define a relation when adding a field

**Comment by marktani** [comment]
Thanks for the feedback, we're searching a better solution here :slightly_smiling_face:
