### ISSUE TITLE
Improve error message when creating an enum

### ISSUE THREAD

**Issue by marcusstenbeck** [graphcool/ui-feedback#12]
Below is an excerpt from my chat.

> I'm having trouble creating an enum.
>
> I fill in "Currencies" as the enum name, and then I create one enum value "usd". I get an error flash saying "'usd' is not a valid name"
>
>Aaahhh I now see that enum values need to start with an uppercase character
>
>"Enum values can only contain alphanumeric characters and underscores and need to start with an uppercase letter. The name of an enum value can be used in query filters and mutations. They can contain maximally 191 characters."
>
>It would be great if the error flash contained that little bit of info. :)

**Comment by marktani** [comment]
Thanks @marcusstenbeck. This is a commonly reported problem 🙂

**Comment by timsuchanek** [comment]
We already have a better message in place :)
