### ISSUE TITLE
Improve billing tab

### ISSUE THREAD

**Issue by marktani** [graphcool/ui-feedback#15]
* in general things are not explained (what do the numbers mean, 5 digits after the dot, ...)
* additionally we need to do a better job at explaining storage overhead

**Comment by joarwilk** [comment]
Payment history dates don't necessarily reflect the actual date of payment. If my transaction date is on the 15th of every month my payment history for the current month will show 0 until the 15th.

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/5a0cb13216a1f51b70dcb0e25e5275d485b01cd7

**Comment by timsuchanek** [comment]
We still don't sync the payment history with the counting month, putting this into a separate issue
