### ISSUE TITLE
Enum creation overflows off screen

### ISSUE THREAD

**Issue by frederickfogerty** [graphcool/ui-feedback#16]
![image](https://cloud.githubusercontent.com/assets/615334/25947742/d058f98c-36a4-11e7-8814-d862cd477fb3.png)

Reproduce:

Enter enum with lowercase name
Click save
Error shows up
Edit name.

**Comment by frederickfogerty** [comment]
Also, I am not able to save the ENUM after this happens. The console says "id not found"

**Comment by marktani** [comment]
Does it work after a reload?

**Comment by frederickfogerty** [comment]
The enum doesn't exist, so I have to re-add it again. I need to get it right first time - if the error shows up, it won't save afterwards

**Comment by timsuchanek** [comment]
Already fixed
