### ISSUE TITLE
Descriptions added to permissions don't persist

### ISSUE THREAD

**Issue by wallslide** [graphcool/ui-feedback#24]
As shown in this video:

https://www.useloom.com/share/dc14b1c9d80c4aec93e0066501d3b9d8

I opened a permission and added a description. No button to save popped up. I then removed/added a comma from the permission query to force the save button to appear. After saving the query and reopening it, the description I wrote no longer exists.

**Comment by timsuchanek** [comment]
Closed in favor of https://github.com/graphcool/console/issues/1169
