### ISSUE TITLE
Indication that the schema shown in console is not Relay compliant

### ISSUE THREAD

**Issue by jhalborg** [graphcool/ui-feedback#26]
There should be some indication and help on the console page that indicates that the schema shown is not Relay compliant, and that it should be fetched differently (https://www.graph.cool/docs/faq/graphql-how-to-download-graphql-idl-schema-maiv5eekan/)

**Comment by marktani** [comment]
When you click the "export schema" button in the schema editor, there's now a popup that allows you to download the full Relay schema.
