### ISSUE TITLE
Chat button hides part of the UI

### ISSUE THREAD

**Issue by mwildric** [graphcool/ui-feedback#3]
<img width="1264" alt="screen shot 2017-03-24 at 5 42 34 pm" src="https://cloud.githubusercontent.com/assets/5809973/24314723/7ce3a8da-10b9-11e7-9ae5-d4afaad67e0e.png">

**Comment by marktani** [comment]
In general the chat is interfering with the UX of the app, even if collapsed.

**Comment by mwildric** [comment]
On Sep 8, 2017 11:57 AM, "Johannes Schickling" <notifications@github.com>
wrote:

Closed #3 <https://github.com/graphcool/ui-feedback/issues/3>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/graphcool/ui-feedback/issues/3#event-1241058537>, or mute
the thread
