### ISSUE TITLE
The function wont work if you are trying to do mutation with-in relation

### ISSUE THREAD

**Issue by iamrommel** [graphcool/ui-feedback#31]
![functionwithmutation](https://cloud.githubusercontent.com/assets/177265/26291759/3e4d9f4c-3ee3-11e7-8b3f-9ad3afe066eb.png)

**Comment by marktani** [comment]
Thanks for the report, this is now fixed!

Please report functional bugs either in [the Console repository](https://github.com/graphcool/console/issues) or [the API bug tracker](https://github.com/graphcool/api-bugs/issues/). This repository is reserved for visual/UI feedback.
