### ISSUE TITLE
Spread operators and destructors are not supported in my functions but in your sample it works well, and i don't know why

### ISSUE THREAD

**Issue by iamrommel** [graphcool/ui-feedback#32]
![transform errors](https://cloud.githubusercontent.com/assets/177265/26291765/5789dc14-3ee3-11e7-8c8b-ae4c3e766c43.png)

**Comment by marktani** [comment]
Thanks, I adjusted all examples to not use the spread operator. This can further be discussed [in this FR](https://github.com/graphcool/feature-requests/issues/227).

**Comment by kbrandwijk** [comment]
Actually, spread operators work fine, you just have to type `"use latest"` at the top of the function
![image](https://user-images.githubusercontent.com/852069/27475997-592f4e04-5807-11e7-9ccd-61cfc57d3874.png)
