### ISSUE TITLE
Console scrolling problem

### ISSUE THREAD

**Issue by gustavopch** [graphcool/ui-feedback#34]
I'm using a Wacom tablet and I scroll using the middle mouse button in the stylus. The editors in the console don't allow me to scroll through code this way. Also, moving the cursor with the keyboard arrows doesn't work properly: going past the last visible line doesn't immediately cause the code editor to scroll.

**Comment by gustavopch** [comment]
Also: scrolling through the right panel unexpectedly causes the text editor to scroll too.

**Comment by kbrandwijk** [comment]
> Also: scrolling through the right panel unexpectedly causes the text editor to scroll too.

That part is fixed in https://github.com/graphcool/console/issues/1072

**Comment by gustavopch** [comment]
Simply reopening the console page wasn't enough - I had to Ctrl+F5. Just saying in case anyone still has the problem.
