### ISSUE TITLE
Save my console navigation menu status to localStorage?

### ISSUE THREAD

**Issue by derBingle** [graphcool/ui-feedback#36]
I'm using Graphcool on a 13" MacBook Pro, so screen space is at premium.

Since the console navigation menu defaults to open, every single time I go to the console, I end up clicking the little collapse menu arrow. Not a big deal, but doing it multiple times a day gets annoying after a while. 😜 

It would be great if the last status of the menu were saved so that it would be collapsed the next time I open the console.

**Comment by timsuchanek** [comment]
done :)

**Comment by kbrandwijk** [comment]
Is it already deployed? Because I think it broke something. Switch the project with the side panel collapsed:
![image](https://user-images.githubusercontent.com/852069/27012705-96f965fc-4ed5-11e7-872e-57840f7a2336.png)
If not related, please move to a new issue.
