### ISSUE TITLE
Error popups in the Console don't allow for copying of the request id

### ISSUE THREAD

**Issue by marktani** [graphcool/ui-feedback#56]
![image](https://user-images.githubusercontent.com/1780597/27680207-47d00960-5cbb-11e7-9338-ef51b04314dd.png)

When you want to copy the request id, you need to find the right request in the network tab of the DevTools...

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/d2029eb4fd227a89a7be689def30f91186b51ae3
