### ISSUE TITLE
Permission query UI is broken

### ISSUE THREAD

**Issue by wallslide** [graphcool/ui-feedback#58]
As you can see, the editor isn't taking up the full width of the modal. Also, the contents of the sidebar, which is normally on the right side of the editor, is instead on the left of the oddly collapsed editor. Fortunately, expanding the editor to fullscreen still works.
![image](https://user-images.githubusercontent.com/917069/27811078-e08ec6b6-609c-11e7-83ae-32f0d694de4a.png)

**Comment by marktani** [comment]
What browser/OS are you experiencing this on? Was this always there case or was it only introduced lately?

**Comment by wallslide** [comment]
It used to be fine. Seems like a recent change broke it for me.

My browser is `Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)` on Windows 10

**Comment by kbrandwijk** [comment]
Two ways to reproduce this, and two parts to this problem. 

1. This screen 'remembers' the docs panel size from the Functions. As the functions screen has more room to show docs, this becomes a problem the next time you go to Permissions:
![reproduce2](https://user-images.githubusercontent.com/852069/27940351-5bca8412-62ca-11e7-8dfc-5f9805af84d3.gif)

2. Also, if you drag the docs panel too wide in Permissions, you can't make it smaller anymore. Only zooming out in the browser gives you access to the border again.
![reproduce](https://user-images.githubusercontent.com/852069/27940175-6a111956-62c9-11e7-8649-20491fab555a.gif)
About the remembering part:

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/6a4c99cb871364f3d6b042a8ca9a9fa3b77b9a71
