### ISSUE TITLE
Webhook URL functionality broken in server-side subscription UI

### ISSUE THREAD

**Issue by wallslide** [graphcool/ui-feedback#64]
Two problems:

*  SSS functions that previously had webhook URLs are now missing their webhook URLs
![image](https://user-images.githubusercontent.com/917069/28008359-26cc78b8-6592-11e7-8c38-591ed2ebffd6.png)

* Adding a webhook URL to the input doesn't re-enable the `Update Function` button.
![image](https://user-images.githubusercontent.com/917069/28008387-5158832e-6592-11e7-9be0-66a9f274c434.png)

* Despite the button showing a disabled state, I can still click it, and it shows the loading animation and eventually disappears as if the new URL was saved. (Alternatively, I can add a comma to the graphql query, and the button changes to an enabled state, and I can click it to update the function).

* After clicking the `Update Function` button and having it "save" the information, if I reopen the saved function, the webhook URL input is once again missing.

* When using the `Test Run` feature, the loading animation continues forever, leading me to believe that the URL is actually missing, and that it's not just a UI artifact.

**Comment by timsuchanek** [comment]
Thanks @wallslide for reporting! As this is a major bug, a better place to report is the console repository. But this issue can remain here right now, I'm immediately fixing it now.

**Comment by timsuchanek** [comment]
It's fixed and the fix is deployed in 10min. Again, thanks for reporting this!
https://github.com/graphcool/console/pull/1204
