### ISSUE TITLE
Permission queries' description text is too cramped

### ISSUE THREAD

**Issue by wallslide** [graphcool/ui-feedback#67]
## Current Situation 

![image](https://user-images.githubusercontent.com/917069/28349449-edac033a-6c7d-11e7-88b7-de54cf66f3a6.png)

## Suggestions

- Instead of having the connect/disconnect text to the right of the description text, move it to a separate row above the description text.
- Don't limit the height or the width of the description text

### Suggestions visualized
![image](https://user-images.githubusercontent.com/917069/28349803-f0092926-6c7f-11e7-98c9-727d5504efc5.png)

**Comment by kbrandwijk** [comment]
@wallslide How can you get a description on a permission query? https://github.com/graphcool/api-bugs/issues/147

**Comment by marktani** [comment]
It works for relation permission queries, but not type permission queries.

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/3028ea425033c407a11cdb442b14223cccdbb206
