### ISSUE TITLE
"Console is not optimized for mobile" on PC 

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/ui-feedback#70]
Hi, 

I'm getting the following on my computer, when trying to work with the console and my code side-by-side. 

<img width="1280" alt="screenshot 2017-07-25 18 49 14" src="https://user-images.githubusercontent.com/1852126/28583797-b3bb4ac2-716a-11e7-8c0c-5e2e821c3e85.png">

I'm using a 2015 MacBook pro, the resolution is 2560 x 1600.

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/632e028442d77ff3f6b0db56bf3d618eec6e872d
