### ISSUE TITLE
Schema editor keeps adding unwanted @rename declarations

### ISSUE THREAD

**Issue by slorber** [graphcool/ui-feedback#72]
Hi,

I've created a GraphQL schema today, with the editor.
I had to do a lot of editions here and there, including schema formatting, ordering fields in type, copy-pasting types...

One thing that was really annoying is that the editor was adding `@rename` statements in many unwanted places

**Comment by timsuchanek** [comment]
Thanks for reporting @slorber ! We not completely removed the auto completion there, as it is a rabbit hole we don't want to go down at the moment.
Closed by https://github.com/graphcool/console/commit/a5aacb7f74c9be106e3fcd7b0227e6729f466dd2
