### ISSUE TITLE
Nodes take a long time to load when adding a relation. 

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/ui-feedback#75]
It's currently hard to add a relation to a node in the databrowser. 

When I click the (not yet set) relation field, the dialogue to select a node pops up. However, the nodes in the popup take awfully long to load (20+ seconds). The rest of the databrowser works normally.

**Comment by marktani** [comment]
This did not yet occur to me, maybe it's related to your specific data structure. Do you have a lot of potentially related nodes, or do they contain a lot of data?
