### ISSUE TITLE
No errors in Function test run

### ISSUE THREAD

**Issue by acorcutt** [graphcool/ui-feedback#78]
I'm not seeing any errors when running functions with 'Test Run' & example event data...

```
module.exports = function (event) {
   return {error: 'There was an error'}
}

module.exports = function (event) {
   throw('an error')
}
```
Possibly related to similar API issue? https://github.com/graphcool/api-bugs/issues/85

The same with external webhooks do show errors.

**Comment by marktani** [comment]
This is already tracked [here](https://github.com/graphcool/console/issues/1207). The `execute/` request in your network tab actually contain an error. I'm closing this in favor of the issue in the Console bug tracker.
