### ISSUE TITLE
Functions Update a bit clumsy especially when going fullscreen mode

### ISSUE THREAD

**Issue by znseven** [graphcool/ui-feedback#79]
When going fullscreen mode for editing a server-side function, you have to close the fullscreen mode then do not close the dialog box but click on Update Function.

It would be nice to have at least a confirmation message on the dialog box closing when changes have been made.

**Comment by timsuchanek** [comment]
Closed by https://github.com/graphcool/console/commit/576d9542d00db1bffef82b100e27e17dd88804ab
