### ISSUE TITLE
Frustrating behavior on number inputs

### ISSUE THREAD

**Issue by wcastand** [graphcool/ui-feedback#81]
Hi, when i fill a number/float input in graph.cool, i have a big frustrating behavior.

By default, there is a 0 in the field but the cursor pop before so if i want to delete it, i just hit the right arrow, but that just switch the field to the next one.

I think it would be a lot better if the behavior was one of the following : 
- by default, there is no value in the input
- by default, when the input is focus, we select the value in it or put the cursor at the end of the value (so we can hit backspace to delete)
- by default, we deactivate the left/right arrow keybinding on input numbers, that way we can use the right/left arrow key to navigate in our field.

Switching field in the form should be done with the `tab` key and not the left/right arrow key.

If you have any question, don't hesitate :)

**Comment by marktani** [comment]
Thanks so much for your detailed description 👌 This experience is indeed frustrating and should be streamlined.
